project:
  type: book
  output-dir: docs
  
book:
  title: "ResearchNote"
  output-file: "docs"
  author: "Kyeong Sun Kim"
  date: "Sept 26 2023"
  site-url: https://kyeongsunkim.github.io
  repo-url: https://github.com/kyeongsunkim/kyeongsunkim.github.io.git
  search: true
  sidebar: 
    style: docked
    background: light
    collapse-level: 2
  chapters:  
    - part: "My Research"
      chapters:
        - index.qmd
        - intro.qmd        
       
format:
  html:
    theme: cosmo
    code-copy: true
    code-fold: true
    toc: true
    toc-depth: 2
    toc-title: On this page
    toc-location: right
    html-math-method: katex
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    minimal: false
    navbar: false

comments:
  hypothesis:
    theme: clean

filters:
  - shinylive
  
self-contained: false
editor: visual
page-navigation: true