# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

from shiny import App, reactive, render, ui

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    ui.h1("Title")

    @render.code
    def greeting():
        return f"Hello, world!\nIt's currently {time()}."
  
    @reactive.calc
    def time():
        reactive.invalidate_later(1)
        return datetime.now()

    ui.h1("Calculate")

    ui.input_slider("x", "Slider value", min=0, max=100, value=10)
    ui.input_action_button("compute", "Compute!")

    @reactive.calc
    async def result():
        return f"Result: {input.x()}"

    # ========================================================================



    return None


_static_assets = ["retirement_files"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "retirement.html",
    server,
    static_assets=_static_assets,
)
